CREATE DATABASE GUIDO_ARMIJO
USE GUIDO_ARMIJO

CREATE TABLE Persona(
Id int PRIMARY KEY IDENTITY(1,1),
Apellidos NVARCHAR(50),
Nombres NVARCHAR(50),
FechaNac DATE,
Estatura NVARCHAR(50),
Sexo INT,
Edad INT
)
CREATE TABLE Mascota(
Id int PRIMARY KEY IDENTITY(1,1),
Especie NVARCHAR(50),
Raza NVARCHAR(50),
Color NVARCHAR(50),
Nombre NVARCHAR(50)
)

SELECT * FROM Persona

SELECT * FROM Mascota